# Reclassification of sleep/ wake stages based on EEG Epochs

In [ ]:
import pandas as pd
from pathlib import Path
import re

# change to where data is downloaded
path = Path('/Users/graceburns/Desktop/brainhack/ds003768-download/sourcedata/')

subject_files = sorted(path.glob("sub-*"))

df_all = []

for subject_file in subject_files:
    # Load TSV file into a DataFrame
    df = pd.read_csv(f'{path}/{subject_file.name}', sep='\t')

    df_groups=df.groupby('session')['30-sec_epoch_sleep_stage'].value_counts().unstack(fill_value=0)
    # Display the first few rows

    df_groups['main_stage'] = df_groups.idxmax(axis=1)
    df_groups['subject'] = re.search(r'sub-\d+', subject_file.name).group(0)
    df_all.append(df_groups)

sleep_stage_df = pd.concat(df_all).fillna(0)

sleep_stage_df['sleep'] = sleep_stage_df[['1', '2', '3']].sum(axis=1)

sleep_stage_df.reset_index(inplace=True)

30-sec_epoch_sleep_stage,session,1,2,W,main_stage,subject,Unscorable,3,1 (uncertain),2 (uncertain),W (uncertain),unscorable,1 (unscorable),2 (unscorable),2 or 3 (unscorable),3 (uncertain),3 (unscorable),sleep
0,task-rest_run-1,1,18.0,1,2,sub-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,19.0
1,task-rest_run-2,3,2.0,15,W,sub-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0
2,task-sleep_run-1,16,11.0,3,1,sub-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,27.0
3,task-sleep_run-2,18,0.0,12,1,sub-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,18.0
4,task-sleep_run-3,15,5.0,10,1,sub-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,task-sleep_run-3,24,6.0,0,1,sub-14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,30.0
96,task-sleep_run-4,24,5.0,1,1,sub-14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,29.0
97,task-sleep_run-5,20,0.0,10,1,sub-14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20.0
98,task-sleep_run-6,26,3.0,1,1,sub-14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,29.0
99,task-sleep_run-7,25,2.0,3,1,sub-14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,27.0

In [ ]:

idx = sleep_stage_df.groupby('subject')['W'].idxmax()

# Select the full rows based on those indices
result = sleep_stage_df.loc[idx]
#result.reset_index(inplace=True)
result.set_index('subject', inplace=True)

# runs with the most wake stage for each participant (only used if sleep is also the mode stage)
result[['session', 'main_stage', 'W']].query("main_stage == 'W'").to_csv('wake_stage_identification.csv')

In [ ]:
idx = sleep_stage_df.groupby('subject')['sleep'].idxmax()

# Select the full rows based on those indices
result = sleep_stage_df.loc[idx]
result.reset_index(inplace=True)
result.set_index('subject', inplace=True)

# runs with the most sleep stage for each participant (only used if sleep is NOT the mode stage)
result[['session', 'main_stage', 'sleep']].query("main_stage != 'W'")

30-sec_epoch_sleep_stage           session main_stage  sleep
subject
sub-01                    task-sleep_run-1          1   27.0
sub-03                    task-sleep_run-1          2   30.0
sub-04                    task-sleep_run-3          2   28.0
sub-06                     task-rest_run-2          1   20.0
sub-07                    task-sleep_run-3          2   30.0
sub-09                    task-sleep_run-5          2   26.0
sub-10                    task-sleep_run-4          2   29.0
sub-11                    task-sleep_run-2          1   25.0
sub-12                    task-sleep_run-3          1   30.0
sub-13                     task-rest_run-1          2   20.0
sub-14                    task-sleep_run-2          1   30.0
sub-15                    task-sleep_run-4          2   30.0
sub-16                    task-sleep_run-1          1   30.0
sub-17                    task-sleep_run-4          1   26.0
sub-18                    task-sleep_run-1          1   26.0
sub-19                    task-sleep_run-1          1   30.0
sub-20                    task-sleep_run-2          1   24.0
sub-21                     task-rest_run-1          1   11.0
sub-22                    task-sleep_run-3          1   30.0
sub-23                    task-sleep_run-4          2   30.0
sub-24                    task-sleep_run-4          2   30.0
sub-25                    task-sleep_run-3          1   26.0
sub-27                    task-sleep_run-3          2   30.0
sub-28                    task-sleep_run-4          2   27.0
sub-29                     task-rest_run-1          2   14.0
sub-30                    task-sleep_run-6          1   30.0
sub-31                    task-sleep_run-1          2   30.0
sub-32                    task-sleep_run-3          2   22.0

In [ ]:
idx = sleep_stage_df.groupby('subject')['1'].idxmax()

# Select the full rows based on those indices
result = sleep_stage_df.loc[idx]
result.reset_index(inplace=True)
result.set_index('subject', inplace=True)

# runs with the most N1
result[['session', 'main_stage', '1']].query("main_stage == '1'")

30-sec_epoch_sleep_stage           session main_stage   1
subject
sub-01                    task-sleep_run-2          1  18
sub-03                    task-sleep_run-6          1  17
sub-04                    task-sleep_run-7          1  23
sub-06                     task-rest_run-2          1  10
sub-07                    task-sleep_run-1          1  28
sub-09                    task-sleep_run-6          1  16
sub-10                    task-sleep_run-2          1  20
sub-11                    task-sleep_run-2          1  25
sub-12                    task-sleep_run-3          1  20
sub-14                    task-sleep_run-1          1  26
sub-15                    task-sleep_run-3          1  25
sub-16                     task-rest_run-2          1  19
sub-17                    task-sleep_run-3          1  22
sub-18                    task-sleep_run-1          1  26
sub-19                    task-sleep_run-1          1  19
sub-20                    task-sleep_run-2          1  24
sub-21                     task-rest_run-1          1  11
sub-22                    task-sleep_run-3          1  30
sub-23                    task-sleep_run-1          1  19
sub-24                    task-sleep_run-6          1  23
sub-25                    task-sleep_run-3          1  26
sub-27                    task-sleep_run-4          1  13
sub-30                    task-sleep_run-1          1  24
sub-31                    task-sleep_run-6          1  25
sub-33                    task-sleep_run-7          1  16

In [ ]:
idx = sleep_stage_df.groupby('subject')['2'].idxmax()

# Select the full rows based on those indices
result = sleep_stage_df.loc[idx]
result.reset_index(inplace=True)
result.set_index('subject', inplace=True)

# runs with the most N2
result[['session', 'main_stage', '2']].query("main_stage == '2'")

30-sec_epoch_sleep_stage           session main_stage     2
subject
sub-01                     task-rest_run-1          2  18.0
sub-03                    task-sleep_run-5          2  29.0
sub-04                    task-sleep_run-3          2  21.0
sub-07                    task-sleep_run-5          2  27.0
sub-09                    task-sleep_run-4          2  20.0
sub-10                    task-sleep_run-4          2  23.0
sub-13                     task-rest_run-1          2  15.0
sub-15                    task-sleep_run-4          2  23.0
sub-16                    task-sleep_run-7          2  28.0
sub-19                    task-sleep_run-5          2  21.0
sub-23                    task-sleep_run-4          2  28.0
sub-24                    task-sleep_run-4          2  25.0
sub-25                     task-rest_run-2          2  18.0
sub-27                    task-sleep_run-3          2  21.0
sub-28                    task-sleep_run-5          2  23.0
sub-29                     task-rest_run-1          2   8.0
sub-30                    task-sleep_run-2          2  13.0
sub-31                     task-rest_run-1          2  18.0
sub-32                    task-sleep_run-3          2  14.0